### ISSUE TITLE
app.py gives error

### ISSUE THREAD

**Issue by dejokz** [plotly/dash-dbx-sql#12]
I have cloned the entire repo, installed my librarires from the requirements.txt.

The [article](https://medium.com/plotly/building-plotly-dash-apps-on-a-lakehouse-with-databricks-sql-b9761c201717) in high-level steps. Step number 4. Run app.py.

It throws an error as below
`ValueError: No valid connection settings.`

**Comment by dejokz** [comment]
Okay. I have resolved this. 
It's because in the article it says that I need to set env variable as HOST_NAME as opposed to SERVER_HOSTNAME as needed by the constant.py file.

Maybe make that correction either in the article or at the code.

**Comment by hannahker** [comment]
Thanks for raising @dejokz! This should be fixed in the blog post now.
